export default {
    "flowers":[
    {
        id:1,
        title:"Пионы",
        img:"flower.jpg",
        oldPrice:"23000тг",
        newPrice:"19000тг"
    },
    {
        id:2,
        title:"Розы",
        img:"rose.jpg",
        oldPrice:"23000тг",
        newPrice:"19000тг"
    },
    {
        id:3,
        title:"Хризантемы",
        img:"hrizan.jpg",
        oldPrice:"23000тг",
        newPrice:"19000тг"
    },
    {
        id:4,
        title:"Ромашки",
        img:"romah.jpg",
        oldPrice:"23000тг",
        newPrice:"19000тг"
    }
    
],
"summerStaff":[
    {
        id:1,
        title:"Пионы",
        img:"flower.jpg",
        oldPrice:"23000тг",
        newPrice:"19000тг"
    },
    {
        id:2,
        title:"Розы",
        img:"rose.jpg",
        oldPrice:"23000тг",
        newPrice:"19000тг"
    },
    {
        id:3,
        title:"Хризантемы",
        img:"hrizan.jpg",
        oldPrice:"23000тг",
        newPrice:"19000тг"
    },
    {
        id:4,
        title:"Ромашки",
        img:"romah.jpg",
        oldPrice:"23000тг",
        newPrice:"19000тг"
    }
]
}